server.port: 8082
eureka.client.service-url.default-zone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create

user.service.url: http://localhost:8080