version: '3.8'

services:
  minio-2:
    image: minio/minio
    hostname: minio2
    ports:
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --address ":9001"
    depends_on:
      - file-server-instance0
      - file-server-instance1
      - file-server-instance2

  minio:
    image: minio/minio
    hostname: minio1
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data
    depends_on:
      - file-server-instance0
      - file-server-instance1
      - file-server-instance2

  file-server-instance0:
    build:
      context: ./practice5-s3-minio
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  file-server-instance1:
    build:
      context: ./practice5-s3-minio
      dockerfile: Dockerfile
    ports:
      - "8081:8080"

  file-server-instance2:
    build:
      context: ./practice5-s3-minio
      dockerfile: Dockerfile
    ports:
      - "8082:8080"

  nginx:
    build:
      context: ./practice5-nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./practice5-nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - file-server-instance0
      - file-server-instance1
      - file-server-instance2
      - minio
      - minio-2