spring.application.name: config-server
server.port: 8888

spring.cloud.config.server.git:
  search-paths:
    - cloud-configs
  clone-on-start: true
  default-label: master
  private-key: "-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAj9rN3gv5sidc05mO8KmEFHevSjMF6ua0zJOKDBu7GI7/2z9i+B7w
qwQGzqQSOozMW1sTi+zlSjwXv4sc97i57YdR+2YVDFRAdRN3bizFigpBnryVl41IGX4rq6
yikHogqdT53uHVqHfgsveSHHRIXkkx/P/U+Qy1u1JoHI1d+n1emiUxb0IFY8IJHwusSKAi
HD+cFbc3dIbGHW0KAvcQIzWuYbSjJRCqDK7nF0nuVDBd7+zezvMsBliW38jllGeZeENmIV
wYSkWKuokxUsfuPlrHFMgzv6kEQAObhcLs1SrnuIz225hKH4oOhgtzO9O9HzWM0siG1Hqp
Azb2dt8jp3BalYAEZ7q7/8trj1WldeDIArwqJAhvAeg7Qn+layyMcvJC9zdSMQNkwcmtR6
HXqZyjvMEmZ3am5V20gxRhrkyX7Vql+0gRQAh66jRYyNHVGcM5rX8L9oIlcHLG3UNZwmHW
m9TwaupXcDedevnAfPWr95/2fMS2pdHuMdswtJmjAAAFmLe+IMe3viDHAAAAB3NzaC1yc2
EAAAGBAI/azd4L+bInXNOZjvCphBR3r0ozBermtMyTigwbuxiO/9s/Yvge8KsEBs6kEjqM
zFtbE4vs5Uo8F7+LHPe4ue2HUftmFQxUQHUTd24sxYoKQZ68lZeNSBl+K6usopB6IKnU+d
7h1ah34LL3khx0SF5JMfz/1PkMtbtSaByNXfp9XpolMW9CBWPCCR8LrEigIhw/nBW3N3SG
xh1tCgL3ECM1rmG0oyUQqgyu5xdJ7lQwXe/s3s7zLAZYlt/I5ZRnmXhDZiFcGEpFirqJMV
LH7j5axxTIM7+pBEADm4XC7NUq57iM9tuYSh+KDoYLczvTvR81jNLIhtR6qQM29nbfI6dw
WpWABGe6u//La49VpXXgyAK8KiQIbwHoO0J/pWssjHLyQvc3UjEDZMHJrUeh16mco7zBJm
d2puVdtIMUYa5Ml+1apftIEUAIeuo0WMjR1RnDOa1/C/aCJXByxt1DWcJh1pvU8GrqV3A3
nXr5wHz1q/ef9nzEtqXR7jHbMLSZowAAAAMBAAEAAAGANJeyHDQUneV2MoY5lBLljvYSx/
XPfAnMn95w4exhgqEFOYr7C+uD4YIfWvzxDSbcr6mkg8ugKHu/0u9xL8ABea23c0nm+BL1
Xdg4GbeUoNsPEpGvvzCP44IVRTZgWKHNv0l18N5v1p+9LrEEYhLBQndQJ0cA/ex/pHSES6
wDZ8jeBU0DvcFNZyNRYmBKJGMnFVzMG8RYKen8FFYBCwR4iebeUipQWwS0pt5q7kDBOVZV
gZn/+3k75zYMMtSn2pHlJZVRFiQLppeuvvyieau6fRlzsDODty9jVpSDTQiVJorllSuOPT
T0YYR9AfKYyQ2XcVH3Vz8P9AbP7fiXkwoXL4c3DJDGFrbW1jl442ACySJ7w30PDp9WVxuQ
FCW6ikrY/aulN1AgWrSqy8LGRJx3GR51LoG68ktcJCOplBKSRwoDgyBfIa1LrP1S6zrqrn
kR2ygobE5O7Bh+9nEPARWugvGXu1cFMtkR+ZaldD9B9pvwqoi4/w5LvmEIYosj83pBAAAA
wQCh8PJ5G5NZCwx0rYLx6zZqYYBA7VWvau/zjILabJNo/jy9pPq4vCQIMdzd2XGEEoJGd5
oGsmwjOfs/POtr1BleMcgXQUHSZ+qSPm+Pm26B0iAISgFN15Fcqu4yTGxV19MysBcKqoQg
lAwKVKMpSwlw9zUAKObH4FmQM5JmMyo/oJ/n0l2VXrtLzP9jYd1VBpA42SEVgxO+denFk2
IV72lPRXyAnfqPn/6HJfLxJWb8EHd3YneuTd3gSDBEXbHYNHUAAADBAMKgG5QwC+Oj4SoD
Rr0vXLFT15YktBJe4pW+sVzytw69j/raPdvt8cu8h6rxvYGO5NcW6sHZkI8IJvE2y8ylMp
8qKiXEE4aoOMQcil0LGDaVB4ak4OiEcc38KS9+M86lrjvK7oFel+Xx4dBt18L76NeLDrPl
6zbkzEgao7psyxF7whKC/AwWFQEnx3gcFKu0niN03sjfx7G6aUyaHQCf6fe6YyiAc+clyd
ZaaVzsply//0pLLRKYTu+XoIeJTUl+RwAAAMEAvTgIhvaFfe5G8I/Q387jAB7yIHPurl4b
Gu2Jz8qhe+RH7WGnuXSmNk3tW6kGCS4wP3i3rbaOeH1SPP1JZb4QNrRh+NbWYx0jRnMkPj
+LhobDaZ6RKey6uCIDt6fLMJlLtFN9dQUtvaNGQBuevBe/PIMct5Sc2HZY8+/ARLidmrfv
RY9ponnmFT2HVZGp/Gwa92VPTl6G6gLZ+4Bk8grzwnKDS9qBtXKdpF73UCzVK23s4r0dcJ
d59CWLxJvXS6vFAAAAHXJvb3RAMzU4Mzg5My12Yzk2ODE2LnR3YzEubmV0AQIDBAU=
-----END OPENSSH PRIVATE KEY-----"
  uri: git@github.com:KLINY1337/term-7-rksp.git
  ignore-local-ssh-settings: true

eureka.client.service-url.default-zone: http://service-discovery:8761/eureka/