spring.application.name: config-server
server.port: 8888

spring.cloud.config.server.git:
  uri: https://github.com/KLINY1337/term-7-rksp
  search-paths:
    - cloud-configs
  skip-ssl-validation: true
  clone-on-start: true
  default-label: master

eureka.client.service-url.default-zone: http://service-discovery:8761/eureka/