services:
  postgres-db1:
    image: postgres:16-alpine3.19
    container_name: postgres-db1
    environment:
      POSTGRES_DB: db1
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
    ports:
      - "5432:5432"
    volumes:
      - db1_data:/var/lib/postgresql/data
    networks:
      - rksp-network

  postgres-db2:
    image: postgres:16-alpine3.19
    container_name: postgres-db2
    environment:
      POSTGRES_DB: db2
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
    ports:
      - "5433:5432"  # Expose on a different port
    volumes:
      - db2_data:/var/lib/postgresql/data
    networks:
      - rksp-network

  postgres-db3:
    image: postgres:16-alpine3.19
    container_name: postgres-db3
    environment:
      POSTGRES_DB: db3
      POSTGRES_USER: user3
      POSTGRES_PASSWORD: password3
    ports:
      - "5434:5432"  # Expose on a different port
    volumes:
      - db3_data:/var/lib/postgresql/data
    networks:
      - rksp-network

  service-discovery:
    build:
      context: ./practice8-service-discovery
    container_name: service-discovery
    ports:
      - "8761:8761"  # Expose on port 8761
    depends_on:
      - postgres-db1
      - postgres-db2
      - postgres-db3
    expose:
      - "8761"
    networks:
      - rksp-network

  config-server:
    build:
      context: ./practice8-config-server
    container_name: config-server
    ports:
      - "8888:8888"  # Expose on port 8888
    depends_on:
      - service-discovery
    expose:
      - "8888"
    networks:
      - rksp-network

  user-service:
    build:
      context: ./practice8-user-service
    container_name: user-service
    ports:
      - "8080:8080"  # Expose on port 8080
    depends_on:
      - user-fullname-service
      - user-role-service
    restart: always
    expose:
      - "8080"
    networks:
      - rksp-network

  user-fullname-service:
    build:
      context: ./practice8-user-fullname-service
    container_name: user-fullname-service
    ports:
      - "8081:8081"  # Expose on port 8081
    depends_on:
      - config-server
    restart: always
    expose:
      - "8081"
    networks:
      - rksp-network

  user-role-service:
    build:
      context: ./practice8-user-role-service
    container_name: user-role-service
    ports:
      - "8082:8082"  # Expose on port 8082
    depends_on:
      - config-server
    restart: always
    expose:
      - "8082"
    networks:
      - rksp-network

  load-balancer:
    build:
      context: ./practice8-load-balancer
    container_name: load-balancer
    ports:
      - "9000:9000"  # Expose on port 9000
    depends_on:
      - user-service
    restart: always
    expose:
      - "9000"
    networks:
      - rksp-network

  api-gateway:
    build:
      context: ./practice8-api-gateway
    container_name: api-gateway
    ports:
      - "80:80"  # Expose on port 80
    depends_on:
      - load-balancer
    restart: always
    expose:
      - "80"
    networks:
      - rksp-network

volumes:
  db1_data:
  db2_data:
  db3_data:
networks:
  rksp-network: